### ISSUE TITLE
ソースコードダウンロード

### ISSUE THREAD

**Issue by Rookie-999** [Taro-Hayashi/KillerWhale#10]
お世話になります。プログラム初心者です。
商品購入し、ソースコード(キーマップ)をいじりたく、qmkファームウェアをダウンロードしたいのですが、どこからダウンロードすれば良いでしょうか?
パスワードを一つのボタンに設定して、そのボタンを押されればパスワードを入力完了としたく、ダウンロード方法をご教示頂けますと幸いです。

宜しくお願い致します。

**Comment by Taro-Hayashi** [comment]
ソースコードはこちらに公開しています。
https://github.com/Taro-Hayashi/qmk_firmware/tree/tarohayashi/keyboards/tarohayashi/killerwhale/
QMKにつきましてはこちらに導入手順がありますのでご覧ください。
https://docs.qmk.fm/#/ja/newbs_getting_started

**Comment by Rookie-999** [comment]
お世話になっております。
試したのですが、この商品のソースコードが入っていませんでした。
![スクリーンショット 2024-01-18 155241](https://github.com/Taro-Hayashi/KillerWhale/assets/124848369/f0c766fe-4f78-44fb-8808-3363e8bef632)
git clone https://github.com/Taro-Hayashi/qmk_firmware.git と入力してもソースコードは無く、どのようにすれば解決出来るかわかりません。
お手数おかけし申し訳御座いませんが、ご助力頂けますと幸いです。

宜しくお願い致します。

**Comment by Taro-Hayashi** [comment]
ソースコードが入っているのはtarohayashiブランチになっています。通常のcloneではmasterブランチになっておりますのでブランチを切り替えてみてください。よろしくお願いいたします。

**Comment by Rookie-999** [comment]
何度も申し訳御座いません。
ブランチの切り替えがうまくいかないようで、ソースコードが入手出来ません。
プログラム初心者で理解出来ておらず申し訳御座いません。

どこで切り替えを行えば良いでしょうか?

宜しくお願い致します。

**Comment by Taro-Hayashi** [comment]
cloneでダウンロードしたディレクトリに移動して「git checkout tarohayashi」で切り替わると思います。直接ZipファイルをダウンロードしていただくかGitHubデスクトップをお使いいただくこともできます。
申し訳ありませんがGitやGitHubの使い方、コンパイル方法につきましては解説しているサイトをご参照いただければと存じます。よろしくお願いいたします。

**Comment by Rookie-999** [comment]
お世話になっております。
ご教示有難う御座います。切り替えが出来ました。
お手数おかけし申し訳御座いませんでした。とても助かりました。

宜しくお願い致します。

**Comment by Rookie-999** [comment]
お世話になっております。
何度も申し訳ございません。
mysysでmakeしたのですが、hexファイルは作成されませんか？
