### ISSUE TITLE
右手デバイス側がうまく機能しない

### ISSUE THREAD

**Issue by Okamoto0y** [Taro-Hayashi/KillerWhale#11]
初めまして、こちらのキーボード購入者です。
問題が起きているので、質問させて下さい。

■起きている事象は
右手デバイス（トラックボールVer）を接続した際に、なぜか左手デバイスを反転したキーマップになります。
有線で左手デバイスを接続しても反応しません。

左手デバイスを接続した際は、右手デバイスだけが反応しない状況です。
すべての設定や接続方法などを確かめたのですが、わからず、、、、

ちなみに、HP記載の「a」が表示されるのかの動作確認もして挙動は問題ないということはわかっております。

■解消方法について
ラズパイを初期化して改めてファームウェアをDLすれば治りますかね？
ラズパイTYPE Cのものを利用しておりどのように初期化すればも分からなかったので対応方法もご教授いただけると幸いです。

**Comment by Taro-Hayashi** [comment]
>ラズパイを初期化して改めてファームウェアをDLすれば治りますかね？

わかりません。

>ラズパイTYPE Cのものを利用しておりどのように初期化すればも分からなかったので対応方法もご教授いただけると幸いです。

お使いのマイコンボードの製品情報をご確認ください。

ベースユニットのジャンパーでの左右の指定にお間違えはないですか？
また、右手に片手用のファームウェアが書き込まれている可能性もあるので両手用のものを上書きすることもお試しください。

**Comment by Okamoto0y** [comment]
ご回答ありがとうございます。ご提案いただいた内容をもとに対応しますので、もしそれでも解消されなかった場合また相談させて下さい。

**Comment by Okamoto0y** [comment]
こちらジャンパーを修正しましたがやはり、
・トラックボール
・TRSSケーブルの接続がうまくいきませんでした。

基盤の初期不良でしょうか？

**Comment by Taro-Hayashi** [comment]
ご提示の条件からは判断いたしかねますが目に見えて傷などがない限り基板が初期不良品である確率はとても低いです。別のスレッドでもお伝えしましたが交換用の基板の販売は可能なので必要な部位があればご連絡ください。
