### ISSUE TITLE
Build guide picture incorrect

### ISSUE THREAD

**Issue by ykz89** [Taro-Hayashi/KillerWhale#2]
In [this part](https://github.com/Taro-Hayashi/KillerWhale/blob/main/leftside/3_SIDE_DPAD.md#assembling) of the build guide, I believe the example is incorrect for the left hand side.
The PCB should be flipped horizontally and the acrylic part accordingly.

**Comment by Taro-Hayashi** [comment]
I'm sorry. Fixed.
thanks for telling me. I hope it is not irreparable.

**Comment by ykz89** [comment]
Thanks, I was able to correct it. I just wanted to point it out to remove the confusion for future builders.
