### ISSUE TITLE
[🐜 Bug Report]  The Raspberry Pi post/holes are too small.

### ISSUE THREAD

**Issue by kcw-gruntsoftware** [Taro-Hayashi/KillerWhale#5]
## Problem

The instructions ask the maker to add the jumper headers prior to soldering the Raspberry Pi.  The problem is the jumper headers are **too big** for the holes in the board.  

The header jumper posts are standard in size (0.64mm x 0.64mm) but even the header posts provided are too big for the board holes which are roughly 0.8mm. The hole should be: 

`Radius: (640^2 + 640^2 ) ^(1/2) = 0.905mm
`

As a result, the posts are so big they managed to come out of the board

| Board Post |
| ----------- |
|<img width="627" alt="RaspbPIHoles-Too-Small" src="https://github.com/Taro-Hayashi/KillerWhale/assets/113292674/6cc4f91a-956a-410a-b695-8d91954fc0c8">|

**Comment by kcw-gruntsoftware** [comment]
cc: @Taro-Hayashi

**Comment by Taro-Hayashi** [comment]
As I answered in my message to BOOTH, the hole is narrower than usual to conthrough, and I will sell you a replacement if you need one.
You have also inquired to YushaKobo, but it is not good to inquire about the same matter in many different directions.
If you don't pull it out forcibly, there should be no problem. I'll close this thread.

**Comment by kcw-gruntsoftware** [comment]
Hi @Taro-Hayashi ,
I bought two halves and the problem exists with both. I think the issue is the board needs a re-design so that the RPi or the header jumper can easily fall into the holes.  All of the other contact/holes fit perfectly and the components were a delight to add to the board.

As of now, I have had to desolder and destroy 2 RPis because the contacts dont connect to the holes and don't complete the circuit.   The picture in the provided in this issue was because the post of the header was stuck in the too-small hole. Even when gently pulling the jumper and RPi, the lead came up.

Since this is a design fault, I hope you can send the replacement boards directly at no charge  as you have done so in other cases.
