### ISSUE TITLE
Electrostatic Discharge Damaged PCB

### ISSUE THREAD

**Issue by amknopes** [Taro-Hayashi/KillerWhale#8]
Hey! I was using my duo killer whale keyboard, and experienced a static shock on the metal toggle switch. After that, many of the keys don't work anymore. Some keys are always pressed, some don't work at all, some send the wrong keycode, and some activate multiple other keys. Can you add electrostatic discharge protection to the PCB?

**Comment by Taro-Hayashi** [comment]
Hello, I hope you are not injured. I'm leaving the circuit protection to the Raspberry Pi Pico, any ideas?

**Comment by amknopes** [comment]
I'm not hurt at all, thanks for your concern <3 
The damage would've happened between the toggle and the Raspberry Pi Pico. I think something as simple as connecting the toggle's metal to a diode-protected ground would work. Electrostatic discharge just needs a ground path to discharge into so that all the current doesn't go into the rest of the PCB. All the other components should be alright since the toggle is the only one that gets touched with regular use

**Comment by Taro-Hayashi** [comment]
The outer metal part and the foot were not conducting, so I disassembled it and found it insulated. I don't think grounding in this condition will help much.
![IMG_0634](https://github.com/Taro-Hayashi/KillerWhale/assets/87086895/bcde713d-7cd4-48bb-ac59-2737ca3e6c09)
There is a 5-pin part that has legs on the case, but considering that the bottom acrylic also needs to be modified, it may be difficult to change it now.
![P-00300](https://github.com/Taro-Hayashi/KillerWhale/assets/87086895/cce9c6c8-a37c-4b2f-b741-55e8d4a50063)
I apologize for not being able to meet your request. We will continue to consider the possibility.

If you need the base unit board to replace the Raspberry Pi Pico, please contact me by email or BOOTH message so I can send it to you at your expense.
Thank you.

**Comment by amknopes** [comment]
Wow that's fascinating. The shock must've traveled from the casing through the air then. 

I definitely want to purchase another board. Since one keypress is registering as multiple for some keys, I suspect the damage might be in the top unit. Is there electrical testing I can do to determine whether the damage is in the base unit or top unit? 
Where can I find your email?

**Comment by Taro-Hayashi** [comment]
here is my email. rinarinapokegogo at gmail.com. Please let me know the country name and I will calculate the shipping cost and get back to you. Payment will be made by paypal.

Registering keypresses as multiple may be found by examining the diode or path with a tester. I'll send you both the top and base PCBs, though I'll ask for more details if you need help figuring out the cause. And Please keep the switch plate and acrylic parts.
